version: '3.8'

services:
  app:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - .:/app
      - chroma_data:/app/chroma_db
    environment:
      - HUGGINGFACEHUB_API_TOKEN=${HUGGINGFACEHUB_API_TOKEN}
    depends_on:
      - chromadb
    command: >
      sh -c "uvicorn main:app --host 0.0.0.0 --port 8000 --reload"

  chromadb:
    image: chromadb/chroma:latest
    ports:
      - "8001:8000"
    volumes:
      - chroma_data:/chroma/chroma
    environment:
      - ALLOW_RESET=TRUE
      - CHROMA_SERVER_AUTHN_CREDENTIALS=admin:admin
      - CHROMA_SERVER_AUTHN_PROVIDER=chromadb.auth.basic_authn.BasicAuthServerProvider

volumes:
  chroma_data:
