services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: document_retrieval_app
    restart: unless-stopped
    ports:
      - "8001:5000"
    volumes:
      - .:/app
      - ./uploads:/app/uploads
    environment:
      - PYTHONUNBUFFERED=1
      - PYTHONPATH=/app
      - OLLAMA_HOST=ollama:11434
      - OLLAMA_MODEL=llama3
    depends_on:
      - ollama
    command: >
      sh -c "uvicorn main:app --host 0.0.0.0 --port 5000 --reload"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/api/docs"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s
    networks:
      - app-network

  ollama:
    image: ollama/ollama:latest
    container_name: ollama
    ports:
      - "11434:11434"
    volumes:
      - ollama_data:/root/.ollama
    networks:
      - app-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:11434/api/tags"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s

networks:
  app-network:
    driver: bridge

volumes:
  ollama_data: